Lumin-the-Awesome-page-builder/Lumin-frontend

- check-coverage.sh
Изменение test coverage конфигурации
> build(CI): changing test coverage configuration

- .eslintrc.js
- package-lock.json
- package.json
Update ветки для дальнейшей демонстрации работы CI
> build(CI): update configuration

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
Данный PR модифицирует процесс CI (смена таски на build).
> build(CI): update CI configuration

- .eslintrc.js
Обновление правил для eslint
- [*] Другие изменения
> build(lint): update eslint rules

- src/assets/bootstrap.css
- src/assets/editor.css
- src/components/editor/Controls.vue
- src/components/editor/Editor.vue
- src/components/editor/Workspace.vue
- src/editor/App.ts
- src/editor/components/Container.ts
- src/editor/core/Packager.ts
- src/editor/core/component/Component.ts
- src/editor/plugin.ts
- test/editor/app.test.ts
- test/editor/core/packager.test.ts
Разработан модуль для упаковки страницы в blob и\или json для последующей скачки пользователем или отправки на сервер для сохранения
полное покрытие Unit тестами
> Editor pack module

- .eslintrc.js
- src/components/editor/Editor.vue
- src/editor/App.ts
- src/editor/core/component/Component.ts
- test/editor/app.test.ts
- test/editor/core/component.test.ts
- test/editor/core/packager.test.ts
Реализованы: создание ивентов на компоненты при их создании, хендлеры этих ивентов и подписка на ивенты приложением  
Написаный функционал был покрыт тестами.
> Editor events

- src/editor/App.ts
- src/editor/core/component/Component.ts
- test/editor/app.test.ts
- test/editor/core/component.test.ts
Разработаны основные методы для манипуляции с элементами дерева: Добавление \ Удалление \ Обновление элементов
Полное покрытие Unit тестами
> feat(core): add \ remove \ update methods for managing tree items

- src/editor/core/property/MultipleProperty.ts
- test/editor/core/multiple-property.test.ts
Добавление Multiple Property (позволяет на один элемент устанавливать несколько параметров)
Полное покрытие unit-тестами
> feat(core): add multiple property

- src/components/editor/Editor.vue
- src/editor/App.ts
- src/editor/components/Pure.ts
- src/editor/core/Packager.ts
- src/editor/core/component/Component.ts
- src/editor/plugin.ts
- test/editor/app.test.ts
- test/editor/core/packager.test.ts
Добавлена возможность работы с самописными компонентами ( html + css )
Тесты для классов App, Packager и Component обновлены
> feat(core): pure component implementation

- src/components/editor/Editor.vue
- src/editor/App.ts
- src/editor/components/Pure.ts
- src/editor/core/Packager.ts
- src/editor/core/component/Component.ts
- src/editor/core/property/MultipleProperty.ts
- src/editor/core/property/Property.ts
- src/editor/plugin.ts
- src/editor/properties/AlignItemsProp.ts
- src/editor/properties/AlignSelfProp.ts
- src/editor/properties/ColWidthProp.ts
- src/editor/properties/FlexDirectionProp.ts
- src/editor/properties/FlexProp.ts
- src/editor/properties/FlexWrapProp.ts
- src/editor/properties/GutterProp.ts
- src/editor/properties/JustifyContentProp.ts
- test/editor/app.test.ts
- test/editor/core/multiple-property.test.ts
- test/editor/core/packager.test.ts
- test/editor/core/property.test.ts
- test/editor/properties/align-items-prop.test.ts
- test/editor/properties/align-self-prop.test.ts
- test/editor/properties/col-width.test.ts
- test/editor/properties/flex-direction-prop.test.ts
- test/editor/properties/flex-prop.test.ts
- test/editor/properties/flex-wrap-prop.test.ts
- test/editor/properties/gutter-prop.test.ts
- test/editor/properties/justify-content-prop.test.ts
> Merge from master

- src/api/modules/auth/dto/login/auth-input.dto.ts
- src/api/modules/auth/models/auth.model.ts
- test/api/modules/auth/auth-model.test.ts
- Создан dto класс для входных данных пользователя при авторизации
- Создан класс AuthModel для работы с авторизацией пользователя
Для классов AuthModel, AuthInputDto были написаны Unit тесты.
> Auth model

- src/editor/components/Container.ts
- src/editor/components/Header.ts
- src/editor/components/Image.ts
- src/editor/components/Link.ts
- src/editor/components/Text.ts
- src/editor/core/property/MultipleProperty.ts
- src/editor/plugin.ts
- test/editor/components/container.test.ts
- test/editor/components/header.test.ts
- test/editor/components/image.test.ts
- test/editor/components/link.test.ts
- test/editor/components/text.test.ts
В редактор были добавлены новые компоненты: text (p), header(h_), link(a), image(img).
Компоненты были покрыты тестами.
> feat(editor): implemented new components: text, header, link,  image

- src/components/CardComponent.vue
- src/components/CardGrid.vue
- src/components/ProjectPreviewModal.vue
- src/store/project-preview-modal.store.ts
- src/views/DashboardView.vue
- test/components/card-component.test.ts
- test/components/project-preview-modal.test.ts
- test/store/project-preview-modal-store.test.ts
Связка модалки проекта со сторами и API
Покрытие Unit тестами
> feat(app): project preview modal implementation

- src/editor/core/Packager.ts
- src/editor/plugin.ts
Обновился метод создания инстансов класса приложения (теперь есть функция "фабрика", которая создает его со всеми компонентами и пропсами) изменен порядок генерации дерева при выгрузке блоба внутри Packager класса
> Editor core

- package-lock.json
- package.json
- src/App.vue
- src/components/HeaderComponent.vue
- src/components/editor/RSidebarComponent.vue
- src/components/editor/Workspace.vue
- src/store/editor.store.ts
- test/components/header-component.test.ts
- test/components/r-sidebar-component.test.ts
Добавлена возможность создавать проекты, дописаны тесты для header component
Unit тесты методов создания, обновление тестов по Header Component
> feat(app): create project implementation

- src/api/modules/library/models/library.model.ts
- src/api/modules/project/models/project.model.ts
- src/api/modules/widget/models/widget.model.ts
- test/api/modules/library/library-model.test.ts
- test/api/modules/project/project-model.test.ts
- test/api/modules/widget/widget-model.test.ts
Изменение базовых эндпоинтов моделей
> build(app): API base endpoints update

- src/utils/api-model.util.ts
- test/util/api-model-util.test.ts
Наглядное пояснение, почему бэкенды на ts - плохая идея.
> fix(app): refresh request bug (bad json provided) fix

- src/api/modules/project/dto/create-project.dto.ts
- src/components/CardComponent.vue
- src/components/HeaderComponent.vue
- src/components/ProjectPreviewModal.vue
- src/components/editor/Editor.vue
- src/router/index.ts
- src/store/auth.store.ts
- src/store/editor.store.ts
- test/api/modules/project/project-model.test.ts
- test/components/card-component.test.ts
- test/components/editor/mount-editor.test.ts
- test/components/header-component.test.ts
- test/store/auth-store.test.ts
- test/store/editor-store.test.ts
Обновления в процессе создания проекта, теперь по умолчанию создается один пустой контейнер в корне проекта. 
Изменился адрес эдитора на /project/:id/edit
Обновлено dto для создания проекта (исправлена ошибка с "пустой" категорией на создании)
Тесты обновлены в соотвествии с изменениями в модулях
> Project creation

- src/api/conf/app.conf.ts
- src/api/conf/yandex.conf.ts
- src/components/LoginComponent.vue
- src/components/auth/VkAuthComponent.vue
Конфиги хоста для авторизации Яндекса и VK перенесены в app.conf
> build(app): auth configuration updates

- src/components/HeaderComponent.vue
- src/components/LoginComponent.vue
- src/utils/token.util.ts
- test/components/header-component.test.ts
- test/components/login-component.test.ts
- test/util/token-util.test.ts
Создана ссылка на форму регистрации пользователей, а также добавлена кнопка выхода из профиля
> feat(ui): add link on registration form and logout button

- src/components/CardGrid.vue
- src/components/LoginComponent.vue
- src/components/ProjectPreviewModal.vue
Исправлены баги в компонентах
Проверка с помощью существующих Unit тестов
> fix(UI): cardGrid, loginComponent, projectModal

- src/components/RegistrationComponent.vue
На странице регистрации иконки Яндекса и Вк были заменены на настоящую регистрацию и вход через соответственные платформы
> feat(ui): add registration from yandex and vk

- src/components/CardComponent.vue
- src/components/CardGrid.vue
- src/components/ProjectPreviewModal.vue
- src/router/index.ts
Исправление в интерфейсе модального окна проекта и библиотеки проектов
> fix(UI): preview modal and card grid styles fix

- check-coverage.sh
Изменение коснулись скрипта, рассчитывающего тестовое покрытие
> build(CI): patch coverage script

- src/components/modals/ProjectPreviewModal.vue
Finally нормальное превью проекта
> fix(app): project preview modal UI fixes

- src/api/conf/app.conf.ts
- src/components/CardComponent.vue
- src/components/CardGrid.vue
- src/components/DashboardComponent.vue
- src/components/editor/AvailableBlocksComponent.vue
- src/components/editor/AvailableWidgetsComponent.vue
- src/components/editor/BlockComponent.vue
- src/components/editor/Editor.vue
- src/components/modals/DeleteFormComponent.vue
- src/components/modals/ProjectPreviewModal.vue
- src/editor/App.ts
- src/editor/core/component/Component.ts
- src/store/component-setup.store.ts
- src/store/dashboard.store.ts
- src/store/editor.store.ts
- src/store/modals/delete-form-component.store.ts
- src/store/project-preview-modal.store.ts
- test/components/card-grid.test.ts
- test/components/delete-form-component.test.ts
- test/components/editor/mount-editor.test.ts
- test/editor/app.test.ts
- test/editor/core/packager.test.ts
- test/store/delete-form-component-store.test.ts
- test/store/editor-store.test.ts
- test/store/project-preview-modal-store.test.ts
1. Добавлена возможность перемещения компонентов между родителями
2. Исправлен баг с созданием виджета (брался не тот, который под курсором, а тот что сейчас выбран на редактирование в сайдбаре)
3. Исправлен баг с рендерингом виджетов (ключи перетирали друг друга и соотвественно компоненты перетирались внутри стейта приложения)
4. Изменено поведение контекстного меню, теперь при использовании стрелок для перемещения компонента, оно остается активно пока пользователь сам его не закроет.
5. Добавлена возможность поиска по виджетам и компонентам в интерфейсе редактора
6. В интерфейсе заблокированы операции редактирования \ скачивания виджета
7. Исправлено окно превью для корректной отрисовки виджета
8. Исправлен баг Pure компонентов (Если он был root элементом переставала работать …
> Editor updates

- src/api/modules/library/dto/libary-categories.dto.ts
- src/api/modules/library/models/library.model.ts
- src/components/modals/ChangeProjectDataComponent.vue
- src/store/modals/change-data-project-component.store.ts
- test/components/change-data-project-component.test.ts
- test/store/change-data-project-component-store.test.ts
В редакторе при изменении категории проекта происходит запрос на сервер с существующими категориями, отображаются в виде dropdown. После выбора успешно отправляются на сервер и обрабатываются.
Поправлены тесты к соответсвующим компонентам
> feat(categories): uploading categories from the server to dropdown

- src/components/editor/RSidebarComponent.vue
- src/components/modals/ChangeProjectDataComponent.vue
Изменены стили dropdown'a для категорий (подогнано под остальные блоки). Название проекта, имя категории и массив тегов теперь отображается в sidebar'e
> styles(categories): change dropdown styles, provide category name in editor store

- src/components/modals/HelloFormComponent.vue
- src/components/modals/ProjectPreviewModal.vue
Изменен текст в приветсвенном модальном окнe, изменены стили у модального окна preview проекта (исправлены).
> feat(preview): change text in hello modal and styles for preview modal

- src/assets/editor-system-styles.css
- src/assets/editor.css
- src/components/editor/BlockComponent.vue
- src/components/editor/ComponentSetupComponent.vue
- src/components/editor/ContextMenuComponent.vue
- src/components/editor/Editor.vue
- src/components/editor/RSidebarComponent.vue
- src/editor/App.ts
- src/editor/components/Container.ts
- src/editor/core/component/Component.ts
- src/store/component-setup.store.ts
- src/store/editor.store.ts
- test/editor/core/component.test.ts
- test/store/component-setup-store.test.ts
- test/store/editor-store.test.ts
Исправлен баг с перемещением через pure компонент, вылетала ошибка из-за отсутсвия htmlElement-а
Исправлен баг с подписями у блоков и виджетов
Исправлен визуал у превью блоков и виджетов
Исправлен баг с использованием виртуальных ключей (использовались даже тогда, когда не было ordering)
Обновлены стили у элементов редактора и selected элементов
Unit тесты обновлены под изменения
> Editor bug fixes and style improvements

- .gitignore
- package-lock.json
- package.json
- src/main.ts
Добавлена инициализация багтрекера Sentry
> build(bug-tracker): added bug-tracker initialization

- package-lock.json
- src/api/modules/project/models/project-ws.model.ts
- src/components/editor/CursorComponent.vue
- src/components/editor/Editor.vue
- src/components/editor/RSidebarComponent.vue
- src/store/cursor.store.ts
- test/components/editor/mount-editor.test.ts
- test/components/r-sidebar-component.test.ts
Добавлено отображение курсоров других пользователей в момент параллельного редактирования одного проекта
Unit тесты
> feat(app): cursor rendering in collaborative editing mode

- src/assets/editor.css
- src/components/editor/Editor.vue
- src/editor/core/component/Component.ts
Теперь при наведении на элемент, который сейчас редактирует другой пользователь, его фон будет окрашиваться красным. Также рядом с этим элементом будет всплывать окно предупреждения.
> feat(app): added visualization of blocked component and warning window

- src/components/modals/HelloFormComponent.vue
Добавлены стили в HelloFormComponent
> Alinochka proj

- src/components/RegistrationComponent.vue
Добавлена валидация для полей электронной почты и пароля при регистрации. Для электронной почты добавлена маска, для пароля добавлены условия, проверяющие его надежность.
Unit-тесты
> feat(app): input registration validation

- src/store/component-setup.store.ts
- test/store/component-setup-store.test.ts
Добавлена возможность отменить захват выбранного элемента в редакторе.
Unit-тесты
> feat(editor): ability to deselect an element

- src/store/editor.store.ts
Изменен путь rout'a при отправки данных в форму
> fix(form): route path on post data

- src/editor/components/Image.ts
> feat(editor): image component updates

- package-lock.json
- src/components/editor/UI/ImageSrcComponent.vue
Добавлена стилизация для окна с выбором фотографий
Unit-тесты
> Stylization image src component
